const links = {
  ABOUT: "/about",
  PROFILE: "/profile",
  ALL: "/all",
  ARTDETAIL: "/art",
  ARTEDIT: "/art/edit/:id",
  CART: "/cart",
  CONTACT: "/contact-us",
  CUSTOMS: "/customs",
  DRAWINGS: "/drawings",
  ERRORPAGE: "*",
  HOME: "/",
  LIMITED: "/limited",
  LOGIN: "/login",
  MYWORKS: "/myworks",
  NEWART: "/new",
  PAINTINGS: "/paintings",
  PHOTOGRAPHY: "/photography",
  PRINTS: "/prints",
  PRIVACY: "/privacy",
  REGISTER: "/register",
  SCULPTURES: "/sculptures",
  SELL: "/sell",
  TERMS: "/terms",
};
export { links };
